apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: g3-app
spec:
  project: default
  source:
    repoURL: "https://github.com/YeeFei93/simple-service-k8s.git"
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: g3-ns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
