apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: g3-ns
  labels:
    app: simple-service
spec:
  type: ClusterIP
  selector:
    app: simple-service
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
